### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-analytic#132]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [ ] account_analytic_distribution
- [ ] account_analytic_distribution_required
- [ ] account_analytic_line_list
- [ ] account_analytic_no_lines
- [ ] account_analytic_parent
- [ ] account_analytic_required
- [ ] account_asset_analytic
- [ ] analytic_base_department
- [ ] analytic_department
- [ ] analytic_multicurrency
- [ ] analytic_partner
- [ ] analytic_partner_hr_timesheet
- [ ] analytic_partner_hr_timesheet_invoice
- [ ] analytic_secondaxis
- [ ] analytic_secondaxis_multicurrency
- [ ] analytic_secondaxis_project
- [ ] analytic_secondaxis_timesheet
- [ ] analytic_tag_dimension
- [ ] procurement_analytic
- [ ] product_analytic
- [ ] purchase_procurement_analytic
- [ ] sale_procurement_analytic
