### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-analytic#133]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [x] account_analytic_default_account - By @i-vyshnevska - #232 
- [x] account_analytic_distribution - ~~By @nadiaafa - #142~~ - By @cubells - #184 
- [ ] account_analytic_distribution_required
- [ ] account_analytic_line_list
- [ ] account_analytic_no_lines - By @ThomasBinsfeld - #190 
- [x] account_analytic_parent - By @jaumeplanas - #168 
- [x] account_analytic_required - By @arkostyuk - #141 
- [x]  account_analytic_sequence - By @aheficent - #187 
- [ ] account_asset_analytic
- [x] analytic_base_department - By @arkostyuk - #145 
- [x] analytic_department >> analytic_base_department - By @Tonow-c2c - #167 
- [ ] analytic_multicurrency
- [x] analytic_partner - By @cristinamartinrod - #195 
- [ ] analytic_partner_hr_timesheet
- [ ] analytic_partner_hr_timesheet_invoice
- [ ] analytic_secondaxis
- [ ] analytic_secondaxis_multicurrency
- [ ] analytic_secondaxis_project
- [ ] analytic_secondaxis_timesheet
- [x] analytic_tag_dimension - By @arkostyuk - #146 
- [x] analytic_tag_dimension_sale_warning - By @mpanarin - #148 
- [x] analytic_tag_dimension_purchase_warning - By @mpanarin - #149 
- [x] mrp_analytic - By @SalahAdDin - #186 
- [x] ~~procurement_analytic~~ Not needed as procurement.order have dissapeared
- [x] product_analytic - By @chienandalu - #172 
- [x] purchase_procurement_analytic > purchase_mto_analytic - By @gittusr - #204 
- [x] sale_procurement_analytic > purchase_mto_analytic - By @gittusr - #204 
- [x] stock_analytic - By @jaredkipe - #162

**Comment by ghost** [comment]
On `analytic_base_department`

**Comment by ghost** [comment]
On `analytic_tag_dimension`

**Comment by jaredkipe** [comment]
On `stock_analytic` (not on the list?) #161

**Comment by pedrobaeza** [comment]
@jaredkipe it was merged after the branches were created, but now it's added.

**Comment by Tonow-c2c** [comment]
@pedrobaeza analytic_department migrated #167

**Comment by jaumeplanas** [comment]
On `account_analytic_parent` #168

**Comment by SalahAdDin** [comment]
On `mrp_analytic`: https://github.com/OCA/account-analytic/pull/186.

**Comment by ray-odoo** [comment]
Tested v10 account_analytic_default_account in v11 Enterprise today.

After changing for Python 3, works great!

Changes:

(1) https://github.com/OCA/account-analytic/blob/10.0/account_analytic_default_account/models/account_analytic_default_account.py#L34

should be instead:
`for key, value in kw.items():`

(2) https://github.com/OCA/account-analytic/blob/10.0/account_analytic_default_account/models/account_analytic_default_account.py#L63

should be instead two lines:
```
keys = list(keys)
keys.remove('date')
```

**Comment by pedrobaeza** [comment]
@ray-odoo why don't you make a PR?

**Comment by ray-odoo** [comment]
@pedrobaeza Only lack of time - if I get time I will.

**Comment by pedrobaeza** [comment]
Yes, please. It would be great!

**Comment by ilmir-k** [comment]
Hi guys!

We plan to migrate ``analytic_multicurrency`` to v11 but one of the dependency  - the module ``account_analytic_analysis`` - was removed since 9th version.
Does anybody know why? What a module provide the same functionality on v11?

Thanks

**Comment by emagdalenaC2i** [comment]
@pedrobaeza you can check mrp_analytic because it is merged in #186

**Comment by i-vyshnevska** [comment]
account_analytic_default_account in https://github.com/OCA/account-analytic/pull/232

**Comment by emagdalenaC2i** [comment]
@pedrobaeza Please, could yo add a note that analytic_department - By @Tonow-c2c - #167 is integrated in analytic_base_department

Also purchase_procurement_analytic > purchase_mto_analytic - By @gittusr - #204 and sale_procurement_analytic > purchase_mto_analytic - By @gittusr - #204 is renamed as procurement_mto_analytic

**Comment by emagdalenaC2i** [comment]
@pedrobaeza account_analytic_default_account - By @i-vyshnevska - #232 is already merged
