### ISSUE TITLE
Migration to version 9.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-analytic#43]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-9.0
# Modules to migrate
- [ ] analytic_multicurrency
- [ ] analytic_secondaxis
- [ ] account_analytic_line_list
- [ ] analytic_secondaxis_multicurrency
- [ ] analytic_secondaxis_project
- [ ] analytic_partner_hr_timesheet_invoice
- [ ] analytic_partner
- [ ] account_analytic_required - By @yvaucher - #59
- [ ] analytic_partner_hr_timesheet
- [ ] account_analytic_plan_required
- [ ] analytic_secondaxis_timesheet
- [ ] product_analytic - By @grindtildeath - #125
- [x] sale_procurement_analytic - By @cubells - #130 
- [ ] stock analytic - By @mreficent - #81

**Comment by yvaucher** [comment]
Starting to port `account_analytic_required`
