### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/account-analytic#489]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] account_analytic_parent - By @mohammadazeem786 - #501
- [ ] account_analytic_required - By @nguyenminhchien - #541
- [x] account_analytic_sequence - By @victoralmau - #629
- [ ] account_analytic_tag_default
- [x] account_move_update_analytic - By @hbrunn - #559
- [ ] analytic_activity_based_cost - By @Urvisha-OSI - #538
- [x] analytic_base_department - By @hbrunn - #658
- [ ] analytic_partner - By @dreispt - #609
- [ ] analytic_tag_dimension
- [ ] mrp_analytic - By @kjoeldevk - #494
- [x] patch - By @hbrunn - #559
- [x] pos_analytic_by_config - By @chienandalu - #610
- [ ] procurement_mto_analytic
- [x] product_analytic - By @CLaurelB - #594
- [x] product_analytic_sale - By @rousseldenis - #621
- [ ] purchase_analytic
- [x] stock_landed_costs_analytic - By @rov-adhoc - #618
- [ ] stock_picking_analytic - By @yostashiro - #527

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by KM-joel** [comment]
Migration to version 16.0 
- mrp_analytic #494 
@sbidoul

**Comment by mohammadazeem786** [comment]
Migration to version 16.0

- account_analytic_parent https://github.com/OCA/account-analytic/pull/501

**Comment by nicomacr** [comment]
Migration to version 16.0

- stock_analytic #506 
- purchase_stock_analytic #509 
- sale_stock_analytic #511

**Comment by RodrigoBM** [comment]
PR [[MIG] purchase_analytic: Migration to 16.0](https://github.com/OCA/account-analytic/pull/524)

**Comment by Raul-S73** [comment]
@sbidoul Migration to version 16.0:
- mrp_analytic_sale_project https://github.com/OCA/account-analytic/pull/549

**Comment by rafaelbn** [comment]
`account_analytic_required` not needed in Odoo 16 as is included in core. Explained in https://github.com/OCA/account-analytic/pull/541#pullrequestreview-1367483412

**Comment by miquelalzanillas** [comment]
Working on `account_analytic_tag_default`
