### ISSUE TITLE
Migration to version 10.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/account-analytic#70]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-10.0
# Modules to migrate
- [x] account_analytic_distribution - By @cubells - #100 
- [ ] account_analytic_line_list
- [x] account_analytic_no_lines - By @adrienpeiffer - #72 
- [x] account_analytic_parent - By @chienandalu - #114 
- [x] account_analytic_plan_required > account_analytic_distribution_required - By @cubells - #103 
- [x] account_analytic_required - By @alexis-via - #71 
- [x] account_asset_analytic - By @luismontalba - #102 
- [ ] analytic_base_department
- [ ] analytic_department
- [ ] analytic_multicurrency
- [x] analytic_partner - By @luismontalba - #85 
- [x] analytic_partner_hr_timesheet - By @luismontalba - #108 
- [x] analytic_partner_hr_timesheet_invoice - By @luismontalba - #113 
- [ ] analytic_secondaxis
- [ ] analytic_secondaxis_multicurrency
- [ ] analytic_secondaxis_project
- [ ] analytic_secondaxis_timesheet
- [ ] pos_analytic_by_config - By @Cedric-Pigeon - #95 
- [x] product_analytic - By @luismontalba - #107 
- [x] procurement_analytic - By @cubells - #111 
- [x] purchase_procurement_analytic - By @cubells - #131 
- [x] sale_analytic_distribution - By @cubells - #92 
- [x] sale_procurement_analytic - By @cubells - #134 
- [x] stock_analytic - By @aheficent - #117

**Comment by nadiaafa** [comment]
Hi @pedrobaeza, is the module purchase_analytic_distribution not needed anymore in v10?

**Comment by pedrobaeza** [comment]
It's needed, but it's not in the list because it was added in 9.0 after the 10.0 branch creation.
